### PR TITLE
Adds Models and Migrations for problems, upvotes, replies and solutions

### LINKED ISSUE #4: Problems, Solutions, Replies & Upvotes - Database Models (/w associations) & DB Migrations

### PR DESCRIPTION
**Pull request by michaellennox**
This closes #4

### CODE REVIEW

**Comment by giamir** [comment]
The models are fine for me. Just one question about the upvotes. Is the user gonna be able to upvote a reply? Apparently no. For me you can merge! 👍

**Comment by saratateno** [comment]
looks good to me!

**Comment by michaellennox** [comment]
closed #4

**Comment by michaellennox** [comment]
closed #4

**Pull request merged**
