### PR TITLE
Setup travis and coveralls, closes #9

### LINKED ISSUE #9: Set up Travis CI Server

### PR DESCRIPTION
**Pull request by giamir**

### CODE REVIEW

**Comment by michaellennox** [comment]
:+1: not sure why it's showing commits that are already in base though

**Comment by giamir** [comment]
I did the pull request yesterday before you merged your models branch in development. 😅

**Comment by michaellennox** [comment]
Yeah but I thought the pull request would update with the updated stuff, oh well.

**Comment by emmabeynon** [comment]
:+1:

**Pull request merged**
